version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: "npm"
    directory: "/headers.security.Api/Frontend"
    schedule:
      interval: weekly
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly